import Head from 'next/head'

const HeadSeo = () => {
  return (
    <Head>
      <title>🛒 Next Store</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default HeadSeo
